#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgdata
Version  : 0.17.12
Release  : 19
URL      : https://download.gnome.org/sources/libgdata/0.17/libgdata-0.17.12.tar.xz
Source0  : https://download.gnome.org/sources/libgdata/0.17/libgdata-0.17.12.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgdata-data = %{version}-%{release}
Requires: libgdata-lib = %{version}-%{release}
Requires: libgdata-license = %{version}-%{release}
Requires: libgdata-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : gsettings-desktop-schemas
BuildRequires : gtk-doc
BuildRequires : pkgconfig(gcr-base-3)
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(oauth)
BuildRequires : uhttpmock-dev

%description
libgdata
========
libgdata is a GLib-based library for accessing online service APIs using the
GData protocol --- most notably, Google's services. It provides APIs to access
the common Google services, and has full asynchronous support.

%package data
Summary: data components for the libgdata package.
Group: Data

%description data
data components for the libgdata package.


%package dev
Summary: dev components for the libgdata package.
Group: Development
Requires: libgdata-lib = %{version}-%{release}
Requires: libgdata-data = %{version}-%{release}
Provides: libgdata-devel = %{version}-%{release}
Requires: libgdata = %{version}-%{release}

%description dev
dev components for the libgdata package.


%package doc
Summary: doc components for the libgdata package.
Group: Documentation

%description doc
doc components for the libgdata package.


%package lib
Summary: lib components for the libgdata package.
Group: Libraries
Requires: libgdata-data = %{version}-%{release}
Requires: libgdata-license = %{version}-%{release}

%description lib
lib components for the libgdata package.


%package license
Summary: license components for the libgdata package.
Group: Default

%description license
license components for the libgdata package.


%package locales
Summary: locales components for the libgdata package.
Group: Default

%description locales
locales components for the libgdata package.


%package tests
Summary: tests components for the libgdata package.
Group: Default
Requires: libgdata = %{version}-%{release}
Requires: gsettings-desktop-schemas

%description tests
tests components for the libgdata package.


%prep
%setup -q -n libgdata-0.17.12
cd %{_builddir}/libgdata-0.17.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588777982
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dinstalled_tests=true  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libgdata
cp %{_builddir}/libgdata-0.17.12/COPYING %{buildroot}/usr/share/package-licenses/libgdata/caeb68c46fa36651acf592771d09de7937926bb3
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gdata

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GData-0.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/libgdata.deps
/usr/share/vala/vapi/libgdata.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/libgdata/gdata/app/gdata-app-categories.h
/usr/include/libgdata/gdata/atom/gdata-author.h
/usr/include/libgdata/gdata/atom/gdata-category.h
/usr/include/libgdata/gdata/atom/gdata-generator.h
/usr/include/libgdata/gdata/atom/gdata-link.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-calendar.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-event.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-external-id.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-jot.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-language.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-relation.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-website.h
/usr/include/libgdata/gdata/gd/gdata-gd-email-address.h
/usr/include/libgdata/gdata/gd/gdata-gd-im-address.h
/usr/include/libgdata/gdata/gd/gdata-gd-name.h
/usr/include/libgdata/gdata/gd/gdata-gd-organization.h
/usr/include/libgdata/gdata/gd/gdata-gd-phone-number.h
/usr/include/libgdata/gdata/gd/gdata-gd-postal-address.h
/usr/include/libgdata/gdata/gd/gdata-gd-reminder.h
/usr/include/libgdata/gdata/gd/gdata-gd-when.h
/usr/include/libgdata/gdata/gd/gdata-gd-where.h
/usr/include/libgdata/gdata/gd/gdata-gd-who.h
/usr/include/libgdata/gdata/gdata-access-handler.h
/usr/include/libgdata/gdata/gdata-access-rule.h
/usr/include/libgdata/gdata/gdata-authorization-domain.h
/usr/include/libgdata/gdata/gdata-authorizer.h
/usr/include/libgdata/gdata/gdata-batch-operation.h
/usr/include/libgdata/gdata/gdata-batchable.h
/usr/include/libgdata/gdata/gdata-client-login-authorizer.h
/usr/include/libgdata/gdata/gdata-comment.h
/usr/include/libgdata/gdata/gdata-commentable.h
/usr/include/libgdata/gdata/gdata-comparable.h
/usr/include/libgdata/gdata/gdata-download-stream.h
/usr/include/libgdata/gdata/gdata-entry.h
/usr/include/libgdata/gdata/gdata-enums.h
/usr/include/libgdata/gdata/gdata-feed.h
/usr/include/libgdata/gdata/gdata-goa-authorizer.h
/usr/include/libgdata/gdata/gdata-oauth1-authorizer.h
/usr/include/libgdata/gdata/gdata-oauth2-authorizer.h
/usr/include/libgdata/gdata/gdata-parsable.h
/usr/include/libgdata/gdata/gdata-query.h
/usr/include/libgdata/gdata/gdata-service.h
/usr/include/libgdata/gdata/gdata-types.h
/usr/include/libgdata/gdata/gdata-upload-stream.h
/usr/include/libgdata/gdata/gdata-version.h
/usr/include/libgdata/gdata/gdata.h
/usr/include/libgdata/gdata/media/gdata-media-category.h
/usr/include/libgdata/gdata/media/gdata-media-content.h
/usr/include/libgdata/gdata/media/gdata-media-credit.h
/usr/include/libgdata/gdata/media/gdata-media-enums.h
/usr/include/libgdata/gdata/media/gdata-media-thumbnail.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-access-rule.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-calendar.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-event.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-feed.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-query.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-service.h
/usr/include/libgdata/gdata/services/contacts/gdata-contacts-contact.h
/usr/include/libgdata/gdata/services/contacts/gdata-contacts-group.h
/usr/include/libgdata/gdata/services/contacts/gdata-contacts-query.h
/usr/include/libgdata/gdata/services/contacts/gdata-contacts-service.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-access-rule.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-document.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-drawing.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-entry.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-enums.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-feed.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-folder.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-metadata.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-pdf.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-presentation.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-property.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-query.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-service.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-spreadsheet.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-text.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-upload-query.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-enums.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-query.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-result.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-search-query.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-search-result.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-service.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-topic-query.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-topic-result.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-album.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-comment.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-enums.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-feed.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-file.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-query.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-service.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-user.h
/usr/include/libgdata/gdata/services/tasks/gdata-tasks-query.h
/usr/include/libgdata/gdata/services/tasks/gdata-tasks-service.h
/usr/include/libgdata/gdata/services/tasks/gdata-tasks-task.h
/usr/include/libgdata/gdata/services/tasks/gdata-tasks-tasklist.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-category.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-comment.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-content.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-credit.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-enums.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-feed.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-query.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-service.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-state.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-video.h
/usr/lib64/libgdata.so
/usr/lib64/pkgconfig/libgdata.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/gdata/GDataAPPCategories.html
/usr/share/gtk-doc/html/gdata/GDataAccessHandler.html
/usr/share/gtk-doc/html/gdata/GDataAccessRule.html
/usr/share/gtk-doc/html/gdata/GDataAuthor.html
/usr/share/gtk-doc/html/gdata/GDataAuthorizationDomain.html
/usr/share/gtk-doc/html/gdata/GDataAuthorizer.html
/usr/share/gtk-doc/html/gdata/GDataBatchOperation.html
/usr/share/gtk-doc/html/gdata/GDataBatchable.html
/usr/share/gtk-doc/html/gdata/GDataCalendarAccessRule.html
/usr/share/gtk-doc/html/gdata/GDataCalendarCalendar.html
/usr/share/gtk-doc/html/gdata/GDataCalendarEvent.html
/usr/share/gtk-doc/html/gdata/GDataCalendarFeed.html
/usr/share/gtk-doc/html/gdata/GDataCalendarQuery.html
/usr/share/gtk-doc/html/gdata/GDataCalendarService.html
/usr/share/gtk-doc/html/gdata/GDataCategory.html
/usr/share/gtk-doc/html/gdata/GDataClientLoginAuthorizer.html
/usr/share/gtk-doc/html/gdata/GDataComment.html
/usr/share/gtk-doc/html/gdata/GDataCommentable.html
/usr/share/gtk-doc/html/gdata/GDataComparable.html
/usr/share/gtk-doc/html/gdata/GDataContactsContact.html
/usr/share/gtk-doc/html/gdata/GDataContactsGroup.html
/usr/share/gtk-doc/html/gdata/GDataContactsQuery.html
/usr/share/gtk-doc/html/gdata/GDataContactsService.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsAccessRule.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsDocument.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsDrawing.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsEntry.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsFeed.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsFolder.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsMetadata.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsPdf.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsPresentation.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsProperty.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsQuery.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsService.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsSpreadsheet.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsText.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsUploadQuery.html
/usr/share/gtk-doc/html/gdata/GDataDownloadStream.html
/usr/share/gtk-doc/html/gdata/GDataEntry.html
/usr/share/gtk-doc/html/gdata/GDataFeed.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseQuery.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseResult.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseSearchQuery.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseSearchResult.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseService.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseTopicQuery.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseTopicResult.html
/usr/share/gtk-doc/html/gdata/GDataGContactCalendar.html
/usr/share/gtk-doc/html/gdata/GDataGContactEvent.html
/usr/share/gtk-doc/html/gdata/GDataGContactExternalID.html
/usr/share/gtk-doc/html/gdata/GDataGContactJot.html
/usr/share/gtk-doc/html/gdata/GDataGContactLanguage.html
/usr/share/gtk-doc/html/gdata/GDataGContactRelation.html
/usr/share/gtk-doc/html/gdata/GDataGContactWebsite.html
/usr/share/gtk-doc/html/gdata/GDataGDEmailAddress.html
/usr/share/gtk-doc/html/gdata/GDataGDIMAddress.html
/usr/share/gtk-doc/html/gdata/GDataGDName.html
/usr/share/gtk-doc/html/gdata/GDataGDOrganization.html
/usr/share/gtk-doc/html/gdata/GDataGDPhoneNumber.html
/usr/share/gtk-doc/html/gdata/GDataGDPostalAddress.html
/usr/share/gtk-doc/html/gdata/GDataGDReminder.html
/usr/share/gtk-doc/html/gdata/GDataGDWhen.html
/usr/share/gtk-doc/html/gdata/GDataGDWhere.html
/usr/share/gtk-doc/html/gdata/GDataGDWho.html
/usr/share/gtk-doc/html/gdata/GDataGenerator.html
/usr/share/gtk-doc/html/gdata/GDataGoaAuthorizer.html
/usr/share/gtk-doc/html/gdata/GDataLink.html
/usr/share/gtk-doc/html/gdata/GDataMediaCategory.html
/usr/share/gtk-doc/html/gdata/GDataMediaContent.html
/usr/share/gtk-doc/html/gdata/GDataMediaCredit.html
/usr/share/gtk-doc/html/gdata/GDataMediaThumbnail.html
/usr/share/gtk-doc/html/gdata/GDataOAuth1Authorizer.html
/usr/share/gtk-doc/html/gdata/GDataOAuth2Authorizer.html
/usr/share/gtk-doc/html/gdata/GDataParsable.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebAlbum.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebComment.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebFeed.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebFile.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebQuery.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebService.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebUser.html
/usr/share/gtk-doc/html/gdata/GDataQuery.html
/usr/share/gtk-doc/html/gdata/GDataService.html
/usr/share/gtk-doc/html/gdata/GDataTasksQuery.html
/usr/share/gtk-doc/html/gdata/GDataTasksService.html
/usr/share/gtk-doc/html/gdata/GDataTasksTask.html
/usr/share/gtk-doc/html/gdata/GDataTasksTasklist.html
/usr/share/gtk-doc/html/gdata/GDataUploadStream.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeCategory.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeComment.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeContent.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeCredit.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeFeed.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeQuery.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeService.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeState.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeVideo.html
/usr/share/gtk-doc/html/gdata/annotation-glossary.html
/usr/share/gtk-doc/html/gdata/cancellation.png
/usr/share/gtk-doc/html/gdata/ch01.html
/usr/share/gtk-doc/html/gdata/ch02.html
/usr/share/gtk-doc/html/gdata/ch03.html
/usr/share/gtk-doc/html/gdata/ch04.html
/usr/share/gtk-doc/html/gdata/ch05.html
/usr/share/gtk-doc/html/gdata/ch06.html
/usr/share/gtk-doc/html/gdata/ch07.html
/usr/share/gtk-doc/html/gdata/ch08.html
/usr/share/gtk-doc/html/gdata/ch09.html
/usr/share/gtk-doc/html/gdata/ch10.html
/usr/share/gtk-doc/html/gdata/ch11.html
/usr/share/gtk-doc/html/gdata/ch12.html
/usr/share/gtk-doc/html/gdata/ch13.html
/usr/share/gtk-doc/html/gdata/ch14.html
/usr/share/gtk-doc/html/gdata/ch15.html
/usr/share/gtk-doc/html/gdata/ch16.html
/usr/share/gtk-doc/html/gdata/ch17.html
/usr/share/gtk-doc/html/gdata/ch18.html
/usr/share/gtk-doc/html/gdata/ch19.html
/usr/share/gtk-doc/html/gdata/data-flow.png
/usr/share/gtk-doc/html/gdata/gdata-GData-Types.html
/usr/share/gtk-doc/html/gdata/gdata-Version-Information.html
/usr/share/gtk-doc/html/gdata/gdata-overview.html
/usr/share/gtk-doc/html/gdata/gdata-running.html
/usr/share/gtk-doc/html/gdata/gdata.devhelp2
/usr/share/gtk-doc/html/gdata/home.png
/usr/share/gtk-doc/html/gdata/index.html
/usr/share/gtk-doc/html/gdata/ix01.html
/usr/share/gtk-doc/html/gdata/ix02.html
/usr/share/gtk-doc/html/gdata/ix03.html
/usr/share/gtk-doc/html/gdata/ix04.html
/usr/share/gtk-doc/html/gdata/ix05.html
/usr/share/gtk-doc/html/gdata/ix06.html
/usr/share/gtk-doc/html/gdata/ix07.html
/usr/share/gtk-doc/html/gdata/ix08.html
/usr/share/gtk-doc/html/gdata/ix09.html
/usr/share/gtk-doc/html/gdata/ix10.html
/usr/share/gtk-doc/html/gdata/ix11.html
/usr/share/gtk-doc/html/gdata/ix12.html
/usr/share/gtk-doc/html/gdata/ix13.html
/usr/share/gtk-doc/html/gdata/ix14.html
/usr/share/gtk-doc/html/gdata/ix15.html
/usr/share/gtk-doc/html/gdata/ix16.html
/usr/share/gtk-doc/html/gdata/ix17.html
/usr/share/gtk-doc/html/gdata/ix18.html
/usr/share/gtk-doc/html/gdata/ix19.html
/usr/share/gtk-doc/html/gdata/ix20.html
/usr/share/gtk-doc/html/gdata/ix21.html
/usr/share/gtk-doc/html/gdata/ix22.html
/usr/share/gtk-doc/html/gdata/ix23.html
/usr/share/gtk-doc/html/gdata/ix24.html
/usr/share/gtk-doc/html/gdata/ix25.html
/usr/share/gtk-doc/html/gdata/ix26.html
/usr/share/gtk-doc/html/gdata/ix27.html
/usr/share/gtk-doc/html/gdata/left-insensitive.png
/usr/share/gtk-doc/html/gdata/left.png
/usr/share/gtk-doc/html/gdata/pt01.html
/usr/share/gtk-doc/html/gdata/pt02.html
/usr/share/gtk-doc/html/gdata/pt03.html
/usr/share/gtk-doc/html/gdata/pt04.html
/usr/share/gtk-doc/html/gdata/pt05.html
/usr/share/gtk-doc/html/gdata/right-insensitive.png
/usr/share/gtk-doc/html/gdata/right.png
/usr/share/gtk-doc/html/gdata/structure.png
/usr/share/gtk-doc/html/gdata/style.css
/usr/share/gtk-doc/html/gdata/up-insensitive.png
/usr/share/gtk-doc/html/gdata/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgdata.so.22
/usr/lib64/libgdata.so.22.5.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgdata/caeb68c46fa36651acf592771d09de7937926bb3

%files tests
%defattr(-,root,root,-)
/usr/libexec/installed-tests/libgdata/authorization
/usr/libexec/installed-tests/libgdata/buffer
/usr/libexec/installed-tests/libgdata/calendar
/usr/libexec/installed-tests/libgdata/cert.pem
/usr/libexec/installed-tests/libgdata/contacts
/usr/libexec/installed-tests/libgdata/general
/usr/libexec/installed-tests/libgdata/key.pem
/usr/libexec/installed-tests/libgdata/oauth1-authorizer
/usr/libexec/installed-tests/libgdata/oauth2-authorizer
/usr/libexec/installed-tests/libgdata/perf
/usr/libexec/installed-tests/libgdata/photo.jpg
/usr/libexec/installed-tests/libgdata/sample.ogg
/usr/libexec/installed-tests/libgdata/streams
/usr/libexec/installed-tests/libgdata/tasks
/usr/libexec/installed-tests/libgdata/test.doc
/usr/libexec/installed-tests/libgdata/test.ods
/usr/libexec/installed-tests/libgdata/test.odt
/usr/libexec/installed-tests/libgdata/test.ppt
/usr/libexec/installed-tests/libgdata/test.xls
/usr/libexec/installed-tests/libgdata/test_updated.odt
/usr/libexec/installed-tests/libgdata/test_updated_file.ppt
/usr/libexec/installed-tests/libgdata/traces/calendar/access-rule-delete
/usr/libexec/installed-tests/libgdata/traces/calendar/access-rule-get
/usr/libexec/installed-tests/libgdata/traces/calendar/access-rule-insert
/usr/libexec/installed-tests/libgdata/traces/calendar/access-rule-update
/usr/libexec/installed-tests/libgdata/traces/calendar/authentication
/usr/libexec/installed-tests/libgdata/traces/calendar/authentication-async
/usr/libexec/installed-tests/libgdata/traces/calendar/authentication-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/calendar/event-insert
/usr/libexec/installed-tests/libgdata/traces/calendar/event_insert-async
/usr/libexec/installed-tests/libgdata/traces/calendar/event_insert-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/calendar/global-authentication
/usr/libexec/installed-tests/libgdata/traces/calendar/query-all-calendars
/usr/libexec/installed-tests/libgdata/traces/calendar/query-all-calendars-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/calendar/query-events
/usr/libexec/installed-tests/libgdata/traces/calendar/query-events-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/calendar/query-own-calendars
/usr/libexec/installed-tests/libgdata/traces/calendar/query-own-calendars-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/calendar/query_all_calendars-async
/usr/libexec/installed-tests/libgdata/traces/calendar/query_all_calendars-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/calendar/query_events-async
/usr/libexec/installed-tests/libgdata/traces/calendar/query_events-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/calendar/query_own_calendars-async
/usr/libexec/installed-tests/libgdata/traces/calendar/query_own_calendars-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/calendar/setup-query-calendars
/usr/libexec/installed-tests/libgdata/traces/calendar/setup-query-events
/usr/libexec/installed-tests/libgdata/traces/calendar/setup-temp-calendar
/usr/libexec/installed-tests/libgdata/traces/calendar/setup-temp-calendar-acls
/usr/libexec/installed-tests/libgdata/traces/calendar/teardown-insert-event
/usr/libexec/installed-tests/libgdata/traces/calendar/teardown-query-calendars
/usr/libexec/installed-tests/libgdata/traces/calendar/teardown-query-events
/usr/libexec/installed-tests/libgdata/traces/calendar/teardown-temp-calendar
/usr/libexec/installed-tests/libgdata/traces/calendar/teardown-temp-calendar-acls
/usr/libexec/installed-tests/libgdata/traces/contacts/authentication
/usr/libexec/installed-tests/libgdata/traces/contacts/authentication-async
/usr/libexec/installed-tests/libgdata/traces/contacts/authentication-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/contacts/batch
/usr/libexec/installed-tests/libgdata/traces/contacts/batch-async
/usr/libexec/installed-tests/libgdata/traces/contacts/batch-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/contacts/contact-insert
/usr/libexec/installed-tests/libgdata/traces/contacts/contact-update
/usr/libexec/installed-tests/libgdata/traces/contacts/global-authentication
/usr/libexec/installed-tests/libgdata/traces/contacts/group-insert
/usr/libexec/installed-tests/libgdata/traces/contacts/group_insert-async
/usr/libexec/installed-tests/libgdata/traces/contacts/group_insert-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/contacts/photo-add
/usr/libexec/installed-tests/libgdata/traces/contacts/photo-delete
/usr/libexec/installed-tests/libgdata/traces/contacts/photo-get
/usr/libexec/installed-tests/libgdata/traces/contacts/photo_add-async
/usr/libexec/installed-tests/libgdata/traces/contacts/photo_add-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/contacts/photo_delete-async
/usr/libexec/installed-tests/libgdata/traces/contacts/photo_delete-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/contacts/photo_get-async
/usr/libexec/installed-tests/libgdata/traces/contacts/photo_get-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/contacts/query-all-contacts
/usr/libexec/installed-tests/libgdata/traces/contacts/query-all-contacts-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/contacts/query-all-groups
/usr/libexec/installed-tests/libgdata/traces/contacts/query-all-groups-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/contacts/query_all_contacts-async
/usr/libexec/installed-tests/libgdata/traces/contacts/query_all_contacts-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/contacts/query_all_groups-async
/usr/libexec/installed-tests/libgdata/traces/contacts/query_all_groups-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/contacts/setup-batch-async
/usr/libexec/installed-tests/libgdata/traces/contacts/setup-query-all-contacts
/usr/libexec/installed-tests/libgdata/traces/contacts/setup-query-all-groups
/usr/libexec/installed-tests/libgdata/traces/contacts/setup-temp-contact
/usr/libexec/installed-tests/libgdata/traces/contacts/setup-temp-contact-with-photo
/usr/libexec/installed-tests/libgdata/traces/contacts/teardown-batch-async
/usr/libexec/installed-tests/libgdata/traces/contacts/teardown-insert
/usr/libexec/installed-tests/libgdata/traces/contacts/teardown-insert-group
/usr/libexec/installed-tests/libgdata/traces/contacts/teardown-query-all-contacts
/usr/libexec/installed-tests/libgdata/traces/contacts/teardown-query-all-groups
/usr/libexec/installed-tests/libgdata/traces/contacts/teardown-temp-contact
/usr/libexec/installed-tests/libgdata/traces/documents/access-rule-insert
/usr/libexec/installed-tests/libgdata/traces/documents/authentication
/usr/libexec/installed-tests/libgdata/traces/documents/authentication-async
/usr/libexec/installed-tests/libgdata/traces/documents/authentication-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/documents/batch
/usr/libexec/installed-tests/libgdata/traces/documents/batch-async
/usr/libexec/installed-tests/libgdata/traces/documents/batch-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/documents/copy-document
/usr/libexec/installed-tests/libgdata/traces/documents/delete-document
/usr/libexec/installed-tests/libgdata/traces/documents/delete-folder
/usr/libexec/installed-tests/libgdata/traces/documents/download-document
/usr/libexec/installed-tests/libgdata/traces/documents/folders-add-to-folder
/usr/libexec/installed-tests/libgdata/traces/documents/folders-remove-from-folder
/usr/libexec/installed-tests/libgdata/traces/documents/folders_add_to_folder-async
/usr/libexec/installed-tests/libgdata/traces/documents/folders_add_to_folder-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/documents/folders_remove_from_folder-async
/usr/libexec/installed-tests/libgdata/traces/documents/folders_remove_from_folder-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/documents/folders_remove_from_folder-async-epilogue
/usr/libexec/installed-tests/libgdata/traces/documents/global-authentication
/usr/libexec/installed-tests/libgdata/traces/documents/query-all-documents
/usr/libexec/installed-tests/libgdata/traces/documents/query-all-documents-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/documents/query-all-documents-with-folder
/usr/libexec/installed-tests/libgdata/traces/documents/query_all_documents-async
/usr/libexec/installed-tests/libgdata/traces/documents/query_all_documents-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/documents/setup-batch-async
/usr/libexec/installed-tests/libgdata/traces/documents/setup-folders-add-to-folder
/usr/libexec/installed-tests/libgdata/traces/documents/setup-folders-remove-from-folder
/usr/libexec/installed-tests/libgdata/traces/documents/setup-temp-document-spreadsheet
/usr/libexec/installed-tests/libgdata/traces/documents/setup-temp-documents
/usr/libexec/installed-tests/libgdata/traces/documents/setup-temp-folder
/usr/libexec/installed-tests/libgdata/traces/documents/setup-update-document_content-and-metadata-non-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/setup-update-document_content-and-metadata-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/setup-update-document_content-only-non-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/setup-update-document_content-only-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/setup-update-document_metadata-only-non-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-and-metadata-in-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-and-metadata-in-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-and-metadata-in-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-and-metadata-in-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-and-metadata-root-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-and-metadata-root-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-and-metadata-root-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-and-metadata-root-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-only-in-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-only-in-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-only-in-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-only-in-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-only-root-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-only-root-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-only-root-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_content-only-root-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_metadata-only-in-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/setup-upload-document_metadata-only-root-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-batch-async
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-copy-document
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-folders-add-to-folder
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-temp-document
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-temp-documents
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-temp-folder
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-update-document_content-and-metadata-non-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-update-document_content-and-metadata-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-update-document_content-only-non-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-update-document_content-only-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-update-document_metadata-only-non-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-and-metadata-in-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-and-metadata-in-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-and-metadata-in-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-and-metadata-in-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-and-metadata-root-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-and-metadata-root-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-and-metadata-root-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-and-metadata-root-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-only-in-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-only-in-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-only-in-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-only-in-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-only-root-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-only-root-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-only-root-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_content-only-root-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_metadata-only-in-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/teardown-upload-document_metadata-only-root-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/update_content-and-metadata-non-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/update_content-and-metadata-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/update_content-only-non-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/update_content-only-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/update_metadata-only-non-resumable
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-and-metadata-in-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-and-metadata-in-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-and-metadata-in-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-and-metadata-in-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-and-metadata-root-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-and-metadata-root-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-and-metadata-root-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-and-metadata-root-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-only-in-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-only-in-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-only-in-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-only-in-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-only-root-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-only-root-folder-resumable-bin-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-only-root-folder-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_content-only-root-folder-resumable-odt-no-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_metadata-only-in-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/documents/upload_metadata-only-root-folder-non-resumable-odt-convert
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-interactive-data-bad-credentials
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-refresh-authorization
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-request-authentication-uri-async
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-request-authentication-uri-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-request-authentication-uri-sync
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-request-authentication-uri-sync-cancellation
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-request-authorization-async
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-request-authorization-async-bad-credentials
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-request-authorization-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-request-authorization-sync
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-request-authorization-sync-bad-credentials
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/oauth1-authorizer-request-authorization-sync-cancellation
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/setup-oauth1-authorizer-data-authenticated
/usr/libexec/installed-tests/libgdata/traces/oauth1-authorizer/setup-oauth1-authorizer-interactive-data
/usr/libexec/installed-tests/libgdata/traces/oauth2-authorizer/oauth2-authorizer-refresh-authorization-authorized
/usr/libexec/installed-tests/libgdata/traces/oauth2-authorizer/oauth2-authorizer-refresh-authorization-unauthorized
/usr/libexec/installed-tests/libgdata/traces/oauth2-authorizer/oauth2-authorizer-request-authorization-async
/usr/libexec/installed-tests/libgdata/traces/oauth2-authorizer/oauth2-authorizer-request-authorization-async-bad-credentials
/usr/libexec/installed-tests/libgdata/traces/oauth2-authorizer/oauth2-authorizer-request-authorization-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/oauth2-authorizer/oauth2-authorizer-request-authorization-sync
/usr/libexec/installed-tests/libgdata/traces/oauth2-authorizer/oauth2-authorizer-request-authorization-sync-bad-credentials
/usr/libexec/installed-tests/libgdata/traces/oauth2-authorizer/oauth2-authorizer-request-authorization-sync-cancellation
/usr/libexec/installed-tests/libgdata/traces/oauth2-authorizer/setup-oauth2-authorizer-data-authenticated
/usr/libexec/installed-tests/libgdata/traces/picasaweb/authentication
/usr/libexec/installed-tests/libgdata/traces/picasaweb/authentication-async
/usr/libexec/installed-tests/libgdata/traces/picasaweb/authentication-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/picasaweb/comment-delete
/usr/libexec/installed-tests/libgdata/traces/picasaweb/comment-insert
/usr/libexec/installed-tests/libgdata/traces/picasaweb/comment-query
/usr/libexec/installed-tests/libgdata/traces/picasaweb/comment-query-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/picasaweb/comment_delete-async
/usr/libexec/installed-tests/libgdata/traces/picasaweb/comment_delete-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/picasaweb/comment_insert-async
/usr/libexec/installed-tests/libgdata/traces/picasaweb/comment_insert-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/picasaweb/comment_query-async
/usr/libexec/installed-tests/libgdata/traces/picasaweb/comment_query-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/picasaweb/download-photo
/usr/libexec/installed-tests/libgdata/traces/picasaweb/download-thumbnails
/usr/libexec/installed-tests/libgdata/traces/picasaweb/global-authentication
/usr/libexec/installed-tests/libgdata/traces/picasaweb/insert-album
/usr/libexec/installed-tests/libgdata/traces/picasaweb/insert_album-async
/usr/libexec/installed-tests/libgdata/traces/picasaweb/insert_album-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query-all-albums
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query-all-albums-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query-all-albums-with-limits
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query-files
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query-files-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query-files-single
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query-user
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query_all_albums-async
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query_all_albums-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query_files-async
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query_files-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query_user-async
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query_user-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query_user_by_username-async
/usr/libexec/installed-tests/libgdata/traces/picasaweb/query_user_by_username-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/picasaweb/setup-query-all-albums
/usr/libexec/installed-tests/libgdata/traces/picasaweb/setup-query-comments
/usr/libexec/installed-tests/libgdata/traces/picasaweb/setup-query-files
/usr/libexec/installed-tests/libgdata/traces/picasaweb/setup-upload
/usr/libexec/installed-tests/libgdata/traces/picasaweb/teardown-insert-album
/usr/libexec/installed-tests/libgdata/traces/picasaweb/teardown-insert-comment
/usr/libexec/installed-tests/libgdata/traces/picasaweb/teardown-query-all-albums
/usr/libexec/installed-tests/libgdata/traces/picasaweb/teardown-query-comments
/usr/libexec/installed-tests/libgdata/traces/picasaweb/teardown-query-files
/usr/libexec/installed-tests/libgdata/traces/picasaweb/teardown-upload
/usr/libexec/installed-tests/libgdata/traces/picasaweb/upload-default-album
/usr/libexec/installed-tests/libgdata/traces/picasaweb/upload_default_album-async
/usr/libexec/installed-tests/libgdata/traces/picasaweb/upload_default_album-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/tasks/authentication
/usr/libexec/installed-tests/libgdata/traces/tasks/global-authentication
/usr/libexec/installed-tests/libgdata/traces/tasks/setup-delete-task
/usr/libexec/installed-tests/libgdata/traces/tasks/setup-delete-tasklist
/usr/libexec/installed-tests/libgdata/traces/tasks/setup-insert-task
/usr/libexec/installed-tests/libgdata/traces/tasks/setup-list-task
/usr/libexec/installed-tests/libgdata/traces/tasks/setup-list-tasklist
/usr/libexec/installed-tests/libgdata/traces/tasks/setup-update-task
/usr/libexec/installed-tests/libgdata/traces/tasks/setup-update-tasklist
/usr/libexec/installed-tests/libgdata/traces/tasks/task-delete
/usr/libexec/installed-tests/libgdata/traces/tasks/task-insert
/usr/libexec/installed-tests/libgdata/traces/tasks/task-list
/usr/libexec/installed-tests/libgdata/traces/tasks/task-update
/usr/libexec/installed-tests/libgdata/traces/tasks/tasklist-delete
/usr/libexec/installed-tests/libgdata/traces/tasks/tasklist-insert
/usr/libexec/installed-tests/libgdata/traces/tasks/tasklist-insert-unauthorised
/usr/libexec/installed-tests/libgdata/traces/tasks/tasklist-list
/usr/libexec/installed-tests/libgdata/traces/tasks/tasklist-update
/usr/libexec/installed-tests/libgdata/traces/tasks/teardown-delete-task
/usr/libexec/installed-tests/libgdata/traces/tasks/teardown-insert-task
/usr/libexec/installed-tests/libgdata/traces/tasks/teardown-insert-tasklist
/usr/libexec/installed-tests/libgdata/traces/tasks/teardown-list-task
/usr/libexec/installed-tests/libgdata/traces/tasks/teardown-list-tasklist
/usr/libexec/installed-tests/libgdata/traces/tasks/teardown-update-task
/usr/libexec/installed-tests/libgdata/traces/tasks/teardown-update-tasklist
/usr/libexec/installed-tests/libgdata/traces/youtube/authentication
/usr/libexec/installed-tests/libgdata/traces/youtube/authentication-async
/usr/libexec/installed-tests/libgdata/traces/youtube/authentication-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/youtube/batch
/usr/libexec/installed-tests/libgdata/traces/youtube/batch-async
/usr/libexec/installed-tests/libgdata/traces/youtube/batch-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/youtube/categories
/usr/libexec/installed-tests/libgdata/traces/youtube/categories-async
/usr/libexec/installed-tests/libgdata/traces/youtube/categories-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/youtube/comment-delete
/usr/libexec/installed-tests/libgdata/traces/youtube/comment-insert
/usr/libexec/installed-tests/libgdata/traces/youtube/comment-query
/usr/libexec/installed-tests/libgdata/traces/youtube/comment-query-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/youtube/comment_delete-async
/usr/libexec/installed-tests/libgdata/traces/youtube/comment_delete-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/youtube/comment_insert-async
/usr/libexec/installed-tests/libgdata/traces/youtube/comment_insert-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/youtube/comment_query-async
/usr/libexec/installed-tests/libgdata/traces/youtube/comment_query-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/youtube/global-authentication
/usr/libexec/installed-tests/libgdata/traces/youtube/query-related
/usr/libexec/installed-tests/libgdata/traces/youtube/query-related-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/youtube/query-single
/usr/libexec/installed-tests/libgdata/traces/youtube/query-standard-feed
/usr/libexec/installed-tests/libgdata/traces/youtube/query-standard-feed-async-progress-closure
/usr/libexec/installed-tests/libgdata/traces/youtube/query-standard-feed-with-query
/usr/libexec/installed-tests/libgdata/traces/youtube/query-standard-feeds
/usr/libexec/installed-tests/libgdata/traces/youtube/query_related-async
/usr/libexec/installed-tests/libgdata/traces/youtube/query_related-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/youtube/query_single-async
/usr/libexec/installed-tests/libgdata/traces/youtube/query_single-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/youtube/query_standard_feed-async
/usr/libexec/installed-tests/libgdata/traces/youtube/query_standard_feed-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/youtube/setup-batch
/usr/libexec/installed-tests/libgdata/traces/youtube/setup-comment
/usr/libexec/installed-tests/libgdata/traces/youtube/setup-insert-comment
/usr/libexec/installed-tests/libgdata/traces/youtube/teardown-insert-comment
/usr/libexec/installed-tests/libgdata/traces/youtube/teardown-upload
/usr/libexec/installed-tests/libgdata/traces/youtube/upload-async
/usr/libexec/installed-tests/libgdata/traces/youtube/upload-async-cancellation
/usr/libexec/installed-tests/libgdata/traces/youtube/upload-simple
/usr/libexec/installed-tests/libgdata/youtube
/usr/share/installed-tests/libgdata/authorization.test
/usr/share/installed-tests/libgdata/buffer.test
/usr/share/installed-tests/libgdata/calendar.test
/usr/share/installed-tests/libgdata/contacts.test
/usr/share/installed-tests/libgdata/general.test
/usr/share/installed-tests/libgdata/oauth1-authorizer.test
/usr/share/installed-tests/libgdata/oauth2-authorizer.test
/usr/share/installed-tests/libgdata/perf.test
/usr/share/installed-tests/libgdata/streams.test
/usr/share/installed-tests/libgdata/tasks.test
/usr/share/installed-tests/libgdata/youtube.test

%files locales -f gdata.lang
%defattr(-,root,root,-)

