#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgdata
Version  : 0.17.4
Release  : 3
URL      : https://download.gnome.org/core/3.20/3.20.2/sources/libgdata-0.17.4.tar.xz
Source0  : https://download.gnome.org/core/3.20/3.20.2/sources/libgdata-0.17.4.tar.xz
Summary  : GData client library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libgdata-lib
Requires: libgdata-doc
Requires: libgdata-locales
Requires: libgdata-data
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gcr-base-3)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libuhttpmock-0.0)
BuildRequires : pkgconfig(oauth)
BuildRequires : uhttpmock-dev

%description
libgdata
========
libgdata is a GLib-based library for accessing online service APIs using the
GData protocol --- most notably, Google's services. It provides APIs to access
the common Google services, and has full asynchronous support.

%package data
Summary: data components for the libgdata package.
Group: Data

%description data
data components for the libgdata package.


%package dev
Summary: dev components for the libgdata package.
Group: Development
Requires: libgdata-lib
Requires: libgdata-data
Provides: libgdata-devel

%description dev
dev components for the libgdata package.


%package doc
Summary: doc components for the libgdata package.
Group: Documentation

%description doc
doc components for the libgdata package.


%package lib
Summary: lib components for the libgdata package.
Group: Libraries
Requires: libgdata-data

%description lib
lib components for the libgdata package.


%package locales
Summary: locales components for the libgdata package.
Group: Default

%description locales
locales components for the libgdata package.


%prep
%setup -q -n libgdata-0.17.4

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
rm -rf %{buildroot}
%make_install
%find_lang gdata

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/gir-1.0/GData-0.0.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libgdata/gdata/app/gdata-app-categories.h
/usr/include/libgdata/gdata/atom/gdata-author.h
/usr/include/libgdata/gdata/atom/gdata-category.h
/usr/include/libgdata/gdata/atom/gdata-generator.h
/usr/include/libgdata/gdata/atom/gdata-link.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-calendar.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-event.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-external-id.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-jot.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-language.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-relation.h
/usr/include/libgdata/gdata/gcontact/gdata-gcontact-website.h
/usr/include/libgdata/gdata/gd/gdata-gd-email-address.h
/usr/include/libgdata/gdata/gd/gdata-gd-im-address.h
/usr/include/libgdata/gdata/gd/gdata-gd-name.h
/usr/include/libgdata/gdata/gd/gdata-gd-organization.h
/usr/include/libgdata/gdata/gd/gdata-gd-phone-number.h
/usr/include/libgdata/gdata/gd/gdata-gd-postal-address.h
/usr/include/libgdata/gdata/gd/gdata-gd-reminder.h
/usr/include/libgdata/gdata/gd/gdata-gd-when.h
/usr/include/libgdata/gdata/gd/gdata-gd-where.h
/usr/include/libgdata/gdata/gd/gdata-gd-who.h
/usr/include/libgdata/gdata/gdata-access-handler.h
/usr/include/libgdata/gdata/gdata-access-rule.h
/usr/include/libgdata/gdata/gdata-authorization-domain.h
/usr/include/libgdata/gdata/gdata-authorizer.h
/usr/include/libgdata/gdata/gdata-batch-operation.h
/usr/include/libgdata/gdata/gdata-batchable.h
/usr/include/libgdata/gdata/gdata-client-login-authorizer.h
/usr/include/libgdata/gdata/gdata-comment.h
/usr/include/libgdata/gdata/gdata-commentable.h
/usr/include/libgdata/gdata/gdata-comparable.h
/usr/include/libgdata/gdata/gdata-download-stream.h
/usr/include/libgdata/gdata/gdata-entry.h
/usr/include/libgdata/gdata/gdata-enums.h
/usr/include/libgdata/gdata/gdata-feed.h
/usr/include/libgdata/gdata/gdata-goa-authorizer.h
/usr/include/libgdata/gdata/gdata-oauth1-authorizer.h
/usr/include/libgdata/gdata/gdata-oauth2-authorizer.h
/usr/include/libgdata/gdata/gdata-parsable.h
/usr/include/libgdata/gdata/gdata-query.h
/usr/include/libgdata/gdata/gdata-service.h
/usr/include/libgdata/gdata/gdata-types.h
/usr/include/libgdata/gdata/gdata-upload-stream.h
/usr/include/libgdata/gdata/gdata-version.h
/usr/include/libgdata/gdata/gdata.h
/usr/include/libgdata/gdata/media/gdata-media-category.h
/usr/include/libgdata/gdata/media/gdata-media-content.h
/usr/include/libgdata/gdata/media/gdata-media-credit.h
/usr/include/libgdata/gdata/media/gdata-media-enums.h
/usr/include/libgdata/gdata/media/gdata-media-thumbnail.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-access-rule.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-calendar.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-event.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-feed.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-query.h
/usr/include/libgdata/gdata/services/calendar/gdata-calendar-service.h
/usr/include/libgdata/gdata/services/contacts/gdata-contacts-contact.h
/usr/include/libgdata/gdata/services/contacts/gdata-contacts-group.h
/usr/include/libgdata/gdata/services/contacts/gdata-contacts-query.h
/usr/include/libgdata/gdata/services/contacts/gdata-contacts-service.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-access-rule.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-document.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-drawing.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-entry.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-enums.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-feed.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-folder.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-pdf.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-presentation.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-query.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-service.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-spreadsheet.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-text.h
/usr/include/libgdata/gdata/services/documents/gdata-documents-upload-query.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-enums.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-query.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-result.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-search-query.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-search-result.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-service.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-topic-query.h
/usr/include/libgdata/gdata/services/freebase/gdata-freebase-topic-result.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-album.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-comment.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-enums.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-feed.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-file.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-query.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-service.h
/usr/include/libgdata/gdata/services/picasaweb/gdata-picasaweb-user.h
/usr/include/libgdata/gdata/services/tasks/gdata-tasks-query.h
/usr/include/libgdata/gdata/services/tasks/gdata-tasks-service.h
/usr/include/libgdata/gdata/services/tasks/gdata-tasks-task.h
/usr/include/libgdata/gdata/services/tasks/gdata-tasks-tasklist.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-category.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-comment.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-content.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-credit.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-enums.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-feed.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-query.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-service.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-state.h
/usr/include/libgdata/gdata/services/youtube/gdata-youtube-video.h
/usr/lib64/*.so
/usr/lib64/girepository-1.0/GData-0.0.typelib
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/gdata/GDataAPPCategories.html
/usr/share/gtk-doc/html/gdata/GDataAccessHandler.html
/usr/share/gtk-doc/html/gdata/GDataAccessRule.html
/usr/share/gtk-doc/html/gdata/GDataAuthor.html
/usr/share/gtk-doc/html/gdata/GDataAuthorizationDomain.html
/usr/share/gtk-doc/html/gdata/GDataAuthorizer.html
/usr/share/gtk-doc/html/gdata/GDataBatchOperation.html
/usr/share/gtk-doc/html/gdata/GDataBatchable.html
/usr/share/gtk-doc/html/gdata/GDataCalendarAccessRule.html
/usr/share/gtk-doc/html/gdata/GDataCalendarCalendar.html
/usr/share/gtk-doc/html/gdata/GDataCalendarEvent.html
/usr/share/gtk-doc/html/gdata/GDataCalendarFeed.html
/usr/share/gtk-doc/html/gdata/GDataCalendarQuery.html
/usr/share/gtk-doc/html/gdata/GDataCalendarService.html
/usr/share/gtk-doc/html/gdata/GDataCategory.html
/usr/share/gtk-doc/html/gdata/GDataClientLoginAuthorizer.html
/usr/share/gtk-doc/html/gdata/GDataComment.html
/usr/share/gtk-doc/html/gdata/GDataCommentable.html
/usr/share/gtk-doc/html/gdata/GDataComparable.html
/usr/share/gtk-doc/html/gdata/GDataContactsContact.html
/usr/share/gtk-doc/html/gdata/GDataContactsGroup.html
/usr/share/gtk-doc/html/gdata/GDataContactsQuery.html
/usr/share/gtk-doc/html/gdata/GDataContactsService.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsAccessRule.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsDocument.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsDrawing.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsEntry.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsFeed.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsFolder.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsPdf.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsPresentation.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsQuery.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsService.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsSpreadsheet.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsText.html
/usr/share/gtk-doc/html/gdata/GDataDocumentsUploadQuery.html
/usr/share/gtk-doc/html/gdata/GDataDownloadStream.html
/usr/share/gtk-doc/html/gdata/GDataEntry.html
/usr/share/gtk-doc/html/gdata/GDataFeed.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseQuery.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseResult.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseSearchQuery.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseSearchResult.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseService.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseTopicQuery.html
/usr/share/gtk-doc/html/gdata/GDataFreebaseTopicResult.html
/usr/share/gtk-doc/html/gdata/GDataGContactCalendar.html
/usr/share/gtk-doc/html/gdata/GDataGContactEvent.html
/usr/share/gtk-doc/html/gdata/GDataGContactExternalID.html
/usr/share/gtk-doc/html/gdata/GDataGContactJot.html
/usr/share/gtk-doc/html/gdata/GDataGContactLanguage.html
/usr/share/gtk-doc/html/gdata/GDataGContactRelation.html
/usr/share/gtk-doc/html/gdata/GDataGContactWebsite.html
/usr/share/gtk-doc/html/gdata/GDataGDEmailAddress.html
/usr/share/gtk-doc/html/gdata/GDataGDIMAddress.html
/usr/share/gtk-doc/html/gdata/GDataGDName.html
/usr/share/gtk-doc/html/gdata/GDataGDOrganization.html
/usr/share/gtk-doc/html/gdata/GDataGDPhoneNumber.html
/usr/share/gtk-doc/html/gdata/GDataGDPostalAddress.html
/usr/share/gtk-doc/html/gdata/GDataGDReminder.html
/usr/share/gtk-doc/html/gdata/GDataGDWhen.html
/usr/share/gtk-doc/html/gdata/GDataGDWhere.html
/usr/share/gtk-doc/html/gdata/GDataGDWho.html
/usr/share/gtk-doc/html/gdata/GDataGenerator.html
/usr/share/gtk-doc/html/gdata/GDataGoaAuthorizer.html
/usr/share/gtk-doc/html/gdata/GDataLink.html
/usr/share/gtk-doc/html/gdata/GDataMediaCategory.html
/usr/share/gtk-doc/html/gdata/GDataMediaContent.html
/usr/share/gtk-doc/html/gdata/GDataMediaCredit.html
/usr/share/gtk-doc/html/gdata/GDataMediaThumbnail.html
/usr/share/gtk-doc/html/gdata/GDataOAuth1Authorizer.html
/usr/share/gtk-doc/html/gdata/GDataOAuth2Authorizer.html
/usr/share/gtk-doc/html/gdata/GDataParsable.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebAlbum.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebComment.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebFeed.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebFile.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebQuery.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebService.html
/usr/share/gtk-doc/html/gdata/GDataPicasaWebUser.html
/usr/share/gtk-doc/html/gdata/GDataQuery.html
/usr/share/gtk-doc/html/gdata/GDataService.html
/usr/share/gtk-doc/html/gdata/GDataTasksQuery.html
/usr/share/gtk-doc/html/gdata/GDataTasksService.html
/usr/share/gtk-doc/html/gdata/GDataTasksTask.html
/usr/share/gtk-doc/html/gdata/GDataTasksTasklist.html
/usr/share/gtk-doc/html/gdata/GDataUploadStream.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeCategory.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeComment.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeContent.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeCredit.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeFeed.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeQuery.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeService.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeState.html
/usr/share/gtk-doc/html/gdata/GDataYouTubeVideo.html
/usr/share/gtk-doc/html/gdata/annotation-glossary.html
/usr/share/gtk-doc/html/gdata/cancellation.png
/usr/share/gtk-doc/html/gdata/ch01.html
/usr/share/gtk-doc/html/gdata/ch02.html
/usr/share/gtk-doc/html/gdata/ch03.html
/usr/share/gtk-doc/html/gdata/ch04.html
/usr/share/gtk-doc/html/gdata/ch05.html
/usr/share/gtk-doc/html/gdata/ch06.html
/usr/share/gtk-doc/html/gdata/ch07.html
/usr/share/gtk-doc/html/gdata/ch08.html
/usr/share/gtk-doc/html/gdata/ch09.html
/usr/share/gtk-doc/html/gdata/ch10.html
/usr/share/gtk-doc/html/gdata/ch11.html
/usr/share/gtk-doc/html/gdata/ch12.html
/usr/share/gtk-doc/html/gdata/ch13.html
/usr/share/gtk-doc/html/gdata/ch14.html
/usr/share/gtk-doc/html/gdata/ch15.html
/usr/share/gtk-doc/html/gdata/ch16.html
/usr/share/gtk-doc/html/gdata/ch17.html
/usr/share/gtk-doc/html/gdata/ch18.html
/usr/share/gtk-doc/html/gdata/ch19.html
/usr/share/gtk-doc/html/gdata/data-flow.png
/usr/share/gtk-doc/html/gdata/gdata-GData-Types.html
/usr/share/gtk-doc/html/gdata/gdata-Version-Information.html
/usr/share/gtk-doc/html/gdata/gdata-overview.html
/usr/share/gtk-doc/html/gdata/gdata-running.html
/usr/share/gtk-doc/html/gdata/gdata.devhelp2
/usr/share/gtk-doc/html/gdata/home.png
/usr/share/gtk-doc/html/gdata/index.html
/usr/share/gtk-doc/html/gdata/ix01.html
/usr/share/gtk-doc/html/gdata/ix02.html
/usr/share/gtk-doc/html/gdata/ix03.html
/usr/share/gtk-doc/html/gdata/ix04.html
/usr/share/gtk-doc/html/gdata/ix05.html
/usr/share/gtk-doc/html/gdata/ix06.html
/usr/share/gtk-doc/html/gdata/ix07.html
/usr/share/gtk-doc/html/gdata/ix08.html
/usr/share/gtk-doc/html/gdata/ix09.html
/usr/share/gtk-doc/html/gdata/ix10.html
/usr/share/gtk-doc/html/gdata/ix11.html
/usr/share/gtk-doc/html/gdata/ix12.html
/usr/share/gtk-doc/html/gdata/ix13.html
/usr/share/gtk-doc/html/gdata/ix14.html
/usr/share/gtk-doc/html/gdata/ix15.html
/usr/share/gtk-doc/html/gdata/ix16.html
/usr/share/gtk-doc/html/gdata/ix17.html
/usr/share/gtk-doc/html/gdata/ix18.html
/usr/share/gtk-doc/html/gdata/ix19.html
/usr/share/gtk-doc/html/gdata/ix20.html
/usr/share/gtk-doc/html/gdata/ix21.html
/usr/share/gtk-doc/html/gdata/ix22.html
/usr/share/gtk-doc/html/gdata/ix23.html
/usr/share/gtk-doc/html/gdata/left-insensitive.png
/usr/share/gtk-doc/html/gdata/left.png
/usr/share/gtk-doc/html/gdata/pt01.html
/usr/share/gtk-doc/html/gdata/pt02.html
/usr/share/gtk-doc/html/gdata/pt03.html
/usr/share/gtk-doc/html/gdata/pt04.html
/usr/share/gtk-doc/html/gdata/pt05.html
/usr/share/gtk-doc/html/gdata/right-insensitive.png
/usr/share/gtk-doc/html/gdata/right.png
/usr/share/gtk-doc/html/gdata/structure.png
/usr/share/gtk-doc/html/gdata/style.css
/usr/share/gtk-doc/html/gdata/up-insensitive.png
/usr/share/gtk-doc/html/gdata/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*

%files locales -f gdata.lang 
%defattr(-,root,root,-)

